// Sample SpatialScene — simulates the JSON output produced by the Limi AI LLM.
// Used for seeding the database and local development.
// Room: "Main Suite" (1200×900 logical pixels)
//   • 5 light modules
//   • 5 sensor modules
//   • 5 furniture modules

import { ModuleType, ModuleStatus } from "./types";
import type { SpatialScene } from "./types";

const ROOM_ID = "room_main_suite_01";
const CREATED_AT = "2026-01-01T00:00:00.000Z";

export const SEED_SPATIAL_SCENE: SpatialScene = {
  room: {
    id: ROOM_ID,
    name: "Main Suite",
    width: 1200,
    height: 900,
  },

  modules: [
    // ─── Lights ───────────────────────────────────────────────────────────────
    {
      id: "mod_light_001",
      uuid: "A4:CF:12:2D:C5:01",
      name: "Ceiling Light North",
      type: ModuleType.LIGHT,
      x: 200,
      y: 100,
      width: 80,
      height: 80,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: 60,
      properties: { intensity: 85, color: "#FFD700" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_light_002",
      uuid: "A4:CF:12:2D:C5:02",
      name: "Ceiling Light South",
      type: ModuleType.LIGHT,
      x: 800,
      y: 700,
      width: 80,
      height: 80,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: 60,
      properties: { intensity: 60, color: "#FFD700" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_light_003",
      uuid: "A4:CF:12:2D:C5:03",
      name: "Desk Lamp East",
      type: ModuleType.LIGHT,
      x: 1000,
      y: 200,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: 20,
      properties: { intensity: 40, color: "#FFF4E0" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_light_004",
      uuid: "A4:CF:12:2D:C5:04",
      name: "Ambient Strip West",
      type: ModuleType.LIGHT,
      x: 100,
      y: 450,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.OFF,
      powerLimit: 30,
      properties: { intensity: 0, color: "#FF6B35" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_light_005",
      uuid: "A4:CF:12:2D:C5:05",
      name: "Pendant Light Centre",
      type: ModuleType.LIGHT,
      x: 560,
      y: 410,
      width: 80,
      height: 80,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: 100,
      properties: { intensity: 100, color: "#FFFFFF" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },

    // ─── Sensors ───────────────────────────────────────────────────────────────
    {
      id: "mod_sensor_001",
      uuid: "B8:27:EB:3F:A1:11",
      name: "Temperature Sensor",
      type: ModuleType.SENSOR,
      x: 400,
      y: 200,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: {
        sensorType: "temperature",
        value: 22.5,
        unit: "°C",
        lastUpdated: CREATED_AT,
      },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_sensor_002",
      uuid: "B8:27:EB:3F:A1:22",
      name: "Humidity Sensor",
      type: ModuleType.SENSOR,
      x: 700,
      y: 300,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: {
        sensorType: "humidity",
        value: 65,
        unit: "%RH",
        lastUpdated: CREATED_AT,
      },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_sensor_003",
      uuid: "B8:27:EB:3F:A1:33",
      name: "Motion Sensor",
      type: ModuleType.SENSOR,
      x: 300,
      y: 600,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: {
        sensorType: "motion",
        value: 0,
        unit: "",
        lastUpdated: CREATED_AT,
      },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_sensor_004",
      uuid: "B8:27:EB:3F:A1:44",
      name: "CO₂ Sensor",
      type: ModuleType.SENSOR,
      x: 900,
      y: 500,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: {
        sensorType: "co2",
        value: 420,
        unit: "ppm",
        lastUpdated: CREATED_AT,
      },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_sensor_005",
      uuid: "B8:27:EB:3F:A1:55",
      name: "Ambient Light Sensor",
      type: ModuleType.SENSOR,
      x: 600,
      y: 150,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: {
        sensorType: "light",
        value: 850,
        unit: "lux",
        lastUpdated: CREATED_AT,
      },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },

    // ─── Furniture ─────────────────────────────────────────────────────────────
    {
      id: "mod_furn_001",
      uuid: "DC:A6:32:F1:B2:01",
      name: "Executive Desk",
      type: ModuleType.FURNITURE,
      x: 900,
      y: 100,
      width: 200,
      height: 100,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: { furnitureType: "desk" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_furn_002",
      uuid: "DC:A6:32:F1:B2:02",
      name: "Sofa",
      type: ModuleType.FURNITURE,
      x: 150,
      y: 620,
      width: 250,
      height: 100,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: { furnitureType: "sofa" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_furn_003",
      uuid: "DC:A6:32:F1:B2:03",
      name: "Coffee Table",
      type: ModuleType.FURNITURE,
      x: 350,
      y: 650,
      width: 120,
      height: 80,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: { furnitureType: "table" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_furn_004",
      uuid: "DC:A6:32:F1:B2:04",
      name: "Wardrobe",
      type: ModuleType.FURNITURE,
      x: 50,
      y: 100,
      width: 100,
      height: 200,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: { furnitureType: "wardrobe" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: "mod_furn_005",
      uuid: "DC:A6:32:F1:B2:05",
      name: "Corner Plant",
      type: ModuleType.FURNITURE,
      x: 1100,
      y: 700,
      width: 60,
      height: 60,
      rotation: 0,
      status: ModuleStatus.ON,
      powerLimit: null,
      properties: { furnitureType: "plant" },
      metadata: {},
      roomId: ROOM_ID,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
  ],
};
